"""

    Assets in this file are actual survivor assets from the game, e.g. pre-fab
    and/or Vignette Survivors from the Vignette expansions.

    Assets in the modules within this folder are more like attributes of
    survivors, but which attach to them the same way game assets would attach,
    e.g. as attributes.

    What that means is that they're asset dictionaries but the assets, for
    example, color schemes or causes of death, etc. that are not actual game
    assets, but which we want to ultimately manage as if they were.

"""

beta_challenge_scenarios = {
    "adam": {
        "name": "Adam",
        'expansion': 'beta_challenge_scenarios',
        "attribs": {
            "name": "Adam",
            "sex": "M",
            "survival": 4,
            "Insanity": 4,
            "Courage": 6,
            "Understanding": 3,
            "Weapon Proficiency": 3,
            "Strength": 1,
            "weapon_proficiency_type": "sword",
            "fighting_arts": ["timeless_eye"],
            "abilities_and_impairments": ["partner", "sword_specialization"],
        },
#        "storage": [
#            "Leather Mask",
#            "Leather Cuirass",
#            "Leather Bracers",
#            "Leather Skirt",
#            "Leather Boots",
#            "Scrap Sword",
#        ],
    },
    "anna": {
        "name": "Anna",
        'expansion': 'beta_challenge_scenarios',
        "attribs": {
            "name": "Anna",
            "sex": "F",
            "survival": 4,
            "Insanity": 4,
            "Courage": 3,
            "Understanding": 6,
            "Weapon Proficiency": 3,
            "Evasion": 1,
            "weapon_proficiency_type": "spear",
            "fighting_arts": ["leader"],
            "abilities_and_impairments": ["partner", "spear_specialization"],
        },
#        "storage": [
#            "Leather Mask",
#            "Leather Cuirass",
#            "Leather Bracers",
#            "Leather Skirt",
#            "Leather Boots",
#            "King Spear",
#        ],
    },
    "paul_the_survivor": {
        "name": "Paul the Survivor",
        'expansion': 'beta_challenge_scenarios',
        "attribs": {
            "name": "Paul",
            "sex": "M",
            "survival": 5,
            "Insanity": 9,
            "Courage": 3,
            "Understanding": 3,
            "fighting_arts": ["thrill_seeker","clutch_fighter","extra_sense"],
            "disorders": ["rageholic","sworn_enemy"],
        },
        "storage": [
#            "Rawhide Pants",
#            "Rawhide Gloves",
#            "Rawhide Vest",
#            "Rawhide Boots",
#            "Bone Dagger",
#            "Scrap Sword",
#            "Piranha Helm",
#            "Petal Lantern",
        ],
    },
    "candy_and_cola":{
        "name": "Candy & Cola",
        'expansion': 'beta_challenge_scenarios',
        "attribs": {"name": "Candy & Cola", "Movement": 6, "disorders": ["hyperactive"], "sex": "F"},
    },
    "kara_black": {
        "name": "Kara Black",
        'expansion': 'beta_challenge_scenarios',
        "attribs": {
            "name": "Kara Black",
            "survival": 3,
            "Strength": 1,
            "fighting_arts": ["leader","tough"],
            "sex": "F"
        },
#        "storage": [
#            "Founding Stone",
#            "Cloth",
#            "Giant Stone Face"
#        ],
    },
    "messenger_of_the_first_story": {
        "name": "Messenger of the First Story",
        'expansion': 'beta_challenge_scenarios',
        "attribs": {
            "name": "Messenger of the First Story",
            "sex": "F",
            "survival": 6,
            "Insanity": 6,
            "Courage": 6,
            "Strength": 1,
            "Evasion": 1,
            "Speed": 1,
            "fighting_arts": ["last_man_standing"],
        },
#        "storage": [
#            "Screaming Horns",
#            "Screaming Coat",
#            "Screaming Skirt",
#            "Screaming Bracers",
#            "Screaming Leg Warmers",
#            "Monster Grease",
#            "Cat Eye Circlet",
#            "Dried Acanthus",
#            "Arm of the First Tree",
#        ],
    },
    "messenger_of_courage":{
        "name": "Messenger of Courage",
        'expansion': 'beta_challenge_scenarios',
        "attribs": {
            "name": "Messenger of Courage",
            "sex": "F",
            "survival": 6,
            "Insanity": 9,
            "Courage":  9,
            "Understanding": 5,
            "Strength": 1,
            "Evasion": 2,
            "Speed": 2,
            "hunt_xp": 2,
            "Weapon Proficiency": 5,
            "weapon_proficiency_type": "twilight_sword",
            "fighting_arts": ["last_man_standing"],
            "cursed_items": ["twilight_sword"],
            "abilities_and_impairments": ["twilight_sword_specialization"],
            "epithets": ["twilight_sword"],
        },
#        "storage": [
#            "Scout's Tunic",
#            "Fairy Bottle",
#            "Leather Skirt",
#            "Leather Boots",
#            "Leather Bracers",
#            "Feather Mantle",
#            "Twilight Sword"
#        ],
    },
    "messenger_of_humanity":{
        "name":  "Messenger of Humanity",
        'expansion': 'beta_challenge_scenarios',
        "attribs": {
            "name":  "Messenger of Humanity",
            "sex": "M",
            "survival": 10,
            "abilities_and_impairments": ["bitter_frenzy", "solid", "grand_weapon_specialization"],
            "fighting_arts": ["berserker", "crossarm_block", "unconscious_fighter"],
            "disorders": ["rageholic"],
        },
#        "storage": [
#            "Lantern Helm",
#            "Lantern Cuirass",
#            "Lantern Greaves",
#            "Lantern Mail",
#            "Lantern Gauntlets",
#            "Beacon Shield",
#            "Dragon Slayer"
#            "Stone Arm"
#        ],
    },
    "snow_the_savior":{
        "name": "Snow the Savior",
        'expansion': 'beta_challenge_scenarios',
        "attribs": {
            "name": "Snow",
            "sex": "F",
            "survival": 6,
            "Insanity": 8,
            "Courage": 5,
            "Understanding": 5,
            "fighting_arts": ["unconscious_fighter"],
            "abilities_and_impairments": ["red_glow", "blue_glow", "green_glow"]
        },
    },

}

vignettes_of_death_white_gigalion = {
    'breccia': {
        'name': 'Breccia of Deadrock',
        'subtitle': 'of Deadrock',
        'ly': 8,
        'expansion': 'vignettes_of_death_white_gigalion',
        'attribs': {
            'name': 'Breccia',
            'sex': 'F',
            'Insanity': 2,
            'Head': 4,
            'Body': 4,
            'Arms': 4,
            'Waist': 4,
            'Legs': 4,
            'survival': 4,
            'Courage': 1,
            'Understanding': 5,
            'abilities_and_impairments': ['whip_specialization', 'tinker'],
            'fighting_arts': ['mighty_strike'],
            'Weapon Proficiency': 3,
            'weapon_proficiency_type': 'whip',
            'hunt_xp': 5,
            'fixed_survival_actions': ['dodge','encourage','dash'],
        },
    },
    'gadrock': {
        'name': 'Gadrock of Deadrock',
        'subtitle': 'of Deadrock',
        'ly': 8,
        'expansion': 'vignettes_of_death_white_gigalion',
        'attribs': {
            'name': 'Gadrock',
            'sex': 'M',
            'Insanity': 4,
            'Head': 3,
            'Body': 3,
            'Arms': 3,
            'Waist': 3,
            'Legs': 3,
            'survival': 3,
            'Courage': 6,
            'Understanding': 2,
            'abilities_and_impairments': ['stalwart'],
            'disorders': ['hoarder'],
            'fighting_arts': ['orator_of_death'],
            'Weapon Proficiency': 2,
            'weapon_proficiency_type': 'katar',
            'hunt_xp': 4,
            'fixed_survival_actions': ['dodge','encourage','dash'],
        },
    },
    'hungry_basalt': {
        'name': 'Hungry Basalt of Deadrock',
        'subtitle': 'of Deadrock',
        'ly': 8,
        'expansion': 'vignettes_of_death_white_gigalion',
        'attribs': {
            'name': 'Hungry Basalt',
            'sex': 'M',
            'Insanity': 3,
            'Head': 4,
            'Body': 4,
            'Arms': 4,
            'Waist': 4,
            'Legs': 4,
            'survival': 3,
            'Courage': 3,
            'Understanding': 1,
            'abilities_and_impairments': ['prepared'],
            'disorders': ['binge_eating_disorder'],
            'hunt_xp': 1,
            'fixed_survival_actions': ['dodge','encourage','dash'],
        },
    },
    'rock_knight': {
        'name': 'Rock Knight of Deadrock',
        'subtitle': 'of Deadrock',
        'ly': 8,
        'expansion': 'vignettes_of_death_white_gigalion',
        'attribs': {
            'name': 'Rock Knight',
            'sex': 'F',
            'Insanity': 6,
            'Head': 3,
            'Body': 4,
            'Waist': 4,
            'Legs': 4,
            'survival': 3,
            'Strength': 1,
            'Understanding': 2,
            'abilities_and_impairments': ['club_specialization'],
            'disorders': ['squeamish', 'post_traumatic_stress'],
            'fighting_arts': ['kings_step', 'clutch_fighter'],
            'Weapon Proficiency': 4,
            'weapon_proficiency_type': 'club',
            'hunt_xp': 6,
            'fixed_survival_actions': ['dodge','encourage','dash'],
        },
    },
}
